apiVersion: v1
kind: Namespace
metadata:
  name: week1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: week1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: mindxintern02acr01.azurecr.io/api:1.0.0
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: week1
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
